name: Build and Deploy to Firebase QA
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Build Angular
        run: |
          npm install
          npm run build -- --configuration=qa
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project open-public-transport --only hosting:open-public-transport-qa
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
